name: Static Test
on: [push, pull_request]

jobs:
  static:
    name: M2 Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master
        with:
          phpcs_severity: 6
          phpcs_report: full
          args: "--colors"

  phpmd:
    name: M2 Mess Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-mess-detector@master